"""add dispatch fields to orders

Revision ID: 0ed1b7770ad4
Revises: 2324aedc9ab9
Create Date: 2025-12-27 18:18:45.758626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed1b7770ad4'
down_revision = '2324aedc9ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('courier_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dispatched_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('dispatched_at')
        batch_op.drop_column('tracking_number')
        batch_op.drop_column('courier_name')

    # ### end Alembic commands ###
