"""add about page

Revision ID: e1b7d84746bd
Revises: 0ed1b7770ad4
Create Date: 2025-12-28 12:59:47.528062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1b7d84746bd'
down_revision = '0ed1b7770ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('who_title', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('who_content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('why_blocks', sa.JSON(), nullable=False))
        batch_op.alter_column('mission_title',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_column('who_we_are_content')
        batch_op.drop_column('who_we_are_title')
        batch_op.drop_column('hero_image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_image_url', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('who_we_are_title', mysql.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('who_we_are_content', mysql.TEXT(), nullable=False))
        batch_op.alter_column('mission_title',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('why_blocks')
        batch_op.drop_column('who_content')
        batch_op.drop_column('who_title')
        batch_op.drop_column('hero_image')

    # ### end Alembic commands ###
